import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const garet = localFont({
  src: [
    {
      path: "../components/fonts/Garet-Book.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../components/fonts/Garet-Heavy.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-garet",
});

export const metadata = {
  title: "WSDelgado",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body
        className={`${garet.variable} antialiased min-h-screen flex flex-col`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
